spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: ScenarioBasedApplication
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8089
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
